name: 'Saplings - Launch'
description: 'Configures best practices for launching modern Drupal.'
type: 'Site'
install:
  - clamav
  - launch_checklist
  - resource_hints
  - seo_checklist
  - scanner
  - seckit
  - security_review
  - tour
  - unused_modules
config:
  strict: false
  import:
    launch_checklist:
      - tour.tour.launch-checklist
  actions:
    # Set permissions for content editor role.
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
      grantPermissions:
        - 'edit launch_checklist checklistapi checklist'
        - 'edit seo_checklist checklistapi checklist'
