name: 'Saplings - Launch'
description: 'Configures best practices for launching modern Drupal.'
type: 'Site'
install:
  # Core modules
  - tour
  # Contrib modules
  - clamav
  - launch_checklist
  - resource_hints
  - seo_checklist
  - scanner
  - seckit
  - security_review
  - unused_modules
config:
  import:
    # Contrib.
    clamav: '*'
    launch_checklist: '*'
    resource_hints: '*'
    scanner: '*'
    security_review: '*'
  actions:
    # Set permissions for content editor role.
    user.role.content_editor:
      ensure_exists:
        id: content_editor
      grantPermissions:
        - 'edit launch_checklist checklistapi checklist'
        - 'edit seo_checklist checklistapi checklist'
